import SlideShell from './shared/SlideShell';
import { PALETTE, TYPOGRAPHY } from './shared/presentationConstants';

const BASE = import.meta.env.BASE_URL;

/**
 * Slide 9: Main Empirical Result — per-forecaster learned skill over time.
 * Shows how the mechanism differentiates the 7 real forecasters on Elia wind data.
 * Generated by scripts/plot_all_slides.R
 */
export default function ContributionsChartSlide() {
  return (
    <SlideShell title="Main Empirical Result" slideNumber={12}>
      {/* Graph — full space */}
      <div style={{ flex: 1, minHeight: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <img
          src={`${BASE}presentation-plots/real_data_validation.png`}
          alt="Learned skill per forecaster over 17,544 rounds — Naive highest, ARIMA lowest"
          style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', borderRadius: 8 }}
        />
      </div>

      {/* Bottom summary */}
      <div style={{ display: 'flex', gap: 16, marginTop: 8 }}>
        <div style={{ flex: 1, background: 'rgba(46, 139, 139, 0.06)', border: `1.5px solid ${PALETTE.teal}`, borderRadius: 10, padding: '10px 16px', textAlign: 'center' }}>
          <span style={{ fontSize: '1.05rem', fontWeight: 700, color: PALETTE.teal, fontFamily: TYPOGRAPHY.fontFamily }}>
            Mechanism learns who is skilled — improves aggregate by ~1/3
          </span>
        </div>
        <div style={{ flex: 1, background: 'rgba(232, 93, 74, 0.06)', border: `1.5px solid ${PALETTE.coral}`, borderRadius: 10, padding: '10px 16px', textAlign: 'center' }}>
          <span style={{ fontSize: '1.05rem', fontWeight: 700, color: PALETTE.coral, fontFamily: TYPOGRAPHY.fontFamily }}>
            Electricity: ~4% gain (forecasters more similar)
          </span>
        </div>
      </div>
    </SlideShell>
  );
}
