import SlideShell from './shared/SlideShell';
import { PALETTE, TYPOGRAPHY } from './shared/presentationConstants';

const BASE = import.meta.env.BASE_URL;

/**
 * Slide 11: Real Data Validation — ggplot2-generated horizontal bar chart.
 * Shows ΔCRPS % for each method vs equal weights on Elia wind data.
 * Generated by scripts/plot_real_data_validation.R
 */
export default function ContributionsChartSlide() {
  return (
    <SlideShell title="Real Data Validation" slideNumber={11}>
      {/* Graph — full space */}
      <div style={{ flex: 1, minHeight: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
        <img
          src={`${BASE}presentation-plots/real_data_validation.png`}
          alt="ΔCRPS by method vs equal weights on Elia wind data — mechanism highlighted"
          style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain', borderRadius: 8 }}
        />
      </div>

      {/* Bottom summary */}
      <div style={{ display: 'flex', gap: 16, marginTop: 8 }}>
        <div style={{ flex: 1, background: 'rgba(46, 139, 139, 0.06)', border: `1.5px solid ${PALETTE.teal}`, borderRadius: 10, padding: '10px 16px', textAlign: 'center' }}>
          <span style={{ fontSize: '1.05rem', fontWeight: 700, color: PALETTE.teal, fontFamily: TYPOGRAPHY.fontFamily }}>
            Wind: −34% CRPS vs equal
          </span>
        </div>
        <div style={{ flex: 1, background: 'rgba(232, 93, 74, 0.06)', border: `1.5px solid ${PALETTE.coral}`, borderRadius: 10, padding: '10px 16px', textAlign: 'center' }}>
          <span style={{ fontSize: '1.05rem', fontWeight: 700, color: PALETTE.coral, fontFamily: TYPOGRAPHY.fontFamily }}>
            Electricity: −4% (less heterogeneity)
          </span>
        </div>
      </div>
    </SlideShell>
  );
}
